server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 프론트엔드 포드 안에서 백엔드로 가는 통로를 뚫어줍니다.
    location /api {
        # 이 주소는 쿠버네티스 내부 DNS 주소입니다. (브라우저가 몰라도 됨)
        proxy_pass http://gateway-service.app.svc.cluster.local:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}